"""Add core tables

Revision ID: 9b8a0f96605e
Revises: 11a9758a9a63
Create Date: 2026-03-25 05:45:49.438226

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b8a0f96605e'
down_revision: Union[str, Sequence[str], None] = '11a9758a9a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_cache',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('raw_match_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_timeline_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analyzed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('players',
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('tag_line', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_table('coaching_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('critical_moments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('habits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coaching_reports')
    op.drop_table('players')
    op.drop_table('match_cache')
    # ### end Alembic commands ###
