"""Add Flex Queue ranks

Revision ID: 9e692b9927fe
Revises: cb8e7478d9fd
Create Date: 2026-03-29 03:57:21.284545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e692b9927fe'
down_revision: Union[str, Sequence[str], None] = 'cb8e7478d9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('flex_tier', sa.String(), nullable=True))
    op.add_column('players', sa.Column('flex_rank', sa.String(), nullable=True))
    op.add_column('players', sa.Column('flex_league_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'flex_league_points')
    op.drop_column('players', 'flex_rank')
    op.drop_column('players', 'flex_tier')
    # ### end Alembic commands ###
