"""remove_flat_ranks

Revision ID: a5b230f39a26
Revises: 9e692b9927fe
Create Date: 2026-03-29 18:06:52.127496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b230f39a26'
down_revision: Union[str, Sequence[str], None] = '9e692b9927fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('summoner_id', sa.String(), nullable=True))
    op.drop_column('players', 'league_points')
    op.drop_column('players', 'flex_tier')
    op.drop_column('players', 'tier')
    op.drop_column('players', 'rank')
    op.drop_column('players', 'flex_rank')
    op.drop_column('players', 'flex_league_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('flex_league_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('flex_rank', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('rank', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('flex_tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('league_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('players', 'summoner_id')
    # ### end Alembic commands ###
