"""Add extended player fields

Revision ID: cb8e7478d9fd
Revises: 9b8a0f96605e
Create Date: 2026-03-29 03:09:44.945652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8e7478d9fd'
down_revision: Union[str, Sequence[str], None] = '9b8a0f96605e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('summoner_level', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('profile_icon_id', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('tier', sa.String(), nullable=True))
    op.add_column('players', sa.Column('rank', sa.String(), nullable=True))
    op.add_column('players', sa.Column('league_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'league_points')
    op.drop_column('players', 'rank')
    op.drop_column('players', 'tier')
    op.drop_column('players', 'profile_icon_id')
    op.drop_column('players', 'summoner_level')
    # ### end Alembic commands ###
