"""add_role_to_reports

Revision ID: d4ef93748068
Revises: a5b230f39a26
Create Date: 2026-03-29 20:20:13.504595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ef93748068'
down_revision: Union[str, Sequence[str], None] = 'a5b230f39a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaching_reports', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaching_reports', 'role')
    # ### end Alembic commands ###
